services:
  gartic:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=gartic_project.settings
    volumes:
      - .:/app
    restart: unless-stopped
    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate &&
            daphne -b 0.0.0.0 -p 8000 gartic_project.asgi:application"
